### PR TITLE
Request to Add Source

### PR DESCRIPTION
**Pull request by Source-Protocol-Cosmos**
Request to Add Source Protocol Deployment template to [Cloudmos](https://deploy.cloudmos.io/templates)

www.sourceprotocol.io

### CODE REVIEW

**Comment by tombeynon** [comment]
Awesome thank you! I'll include in the next release

**Comment by Source-Protocol-Cosmos** [comment]
Amazing! Thank You!

**Comment by tombeynon** [comment]
Pre-release image: `ghcr.io/akash-network/cosmos-omnibus:v0.4.9-rc2-source-v3.0.1`

**Comment by Source-Protocol-Cosmos** [comment]
Thanks. Is there anything else required on our end?

**Comment by tombeynon** [comment]
Nope all good, releasing now

**Pull request merged**
