### PR TITLE
Upgrade Lum to v1.4.5

### PR DESCRIPTION
**Pull request by moonshine-cc**

### CODE REVIEW

**Comment by tombeynon** [comment]
@moonshine-cc could you split this into two PRs? Qwoyn is failing to build, see action logs

**Comment by moonshine-cc** [comment]
> @moonshine-cc could you split this into two PRs? Qwoyn is failing to build, see action logs

Damned, I'm such a noob, so how would I do this (using the Github website)?

**Comment by moonshine-cc** [comment]
> @moonshine-cc could you split this into two PRs? Qwoyn is failing to build, see action logs

That chain is now officially listed and I just tried to re-run the build action but it still fails, obviously due to

```
note: module requires Go 1.19
```

Any hint?

**Comment by moonshine-cc** [comment]
> @moonshine-cc could you split this into two PRs? Qwoyn is failing to build, see action logs

Tried to read up on how to split a PR, but it seemed to be easier to just revert the addition of qwoyn for now, so the updated PR should be good to go.

**Comment by tombeynon** [comment]
@moonshine-cc You can change the Go version with `GOLANG_VERSION` build argument, as explained in #554. 

The best way to do updates is in a branch for each update you're making, e.g. `update-lum-v1.4.5` instead of using your fork's `master` branch, then submit a PR for that branch to upstream master branch. If you use a single branch like you did originally then you can't separate each update. Hard to explain but it makes sense once you get the hang of it.

This is fine though, I've removed `qwoyn` from publish.yml instead of leaving it commented out as you did.

**Pull request merged**
