### PR TITLE
Upgrade Bitcanna to v3.0.1

### PR DESCRIPTION
**Pull request by rodri-r**

### CODE REVIEW

**Comment by rodri-r** [comment]
Hi @tombeynon 

Not sure why test build is failing

Submitted PR before waiting for tests to complete 😬

ERROR: failed to solve: process "/bin/sh -c apt-get update &&   apt-get install --no-install-recommends --assume-yes ca-certificates curl wget file unzip liblz4-tool gnupg2 jq pv &&   apt-get clean" did not complete successfully: exit code: 127
Error: Process completed with exit code 1.

**Comment by tombeynon** [comment]
Hey @rodri-r - the image needs to be a debian based one, and Go 1.21 doesn't support buster so we also need to bump that to bullseye. Essentially use: 

```
        GOLANG_VERSION: 1.21-bullseye
        DEBIAN_VERSION: bullseye
```

You can see the same config used for dYdX: https://github.com/akash-network/cosmos-omnibus/blob/7456b93913b74b211fc5b7b96fed784f80f74fe6/dydx/build.yml#L15-L16

**Comment by tombeynon** [comment]
`ghcr.io/akash-network/cosmos-omnibus:v0.4.7-rc3-bitcanna-v3.0.0`

**Comment by tombeynon** [comment]
@rodri-r could you leave the Omnibus version as it was (`cosmos-omnibus:v0.4.6` instead of `cosmos-omnibus:v0.4.7`) and only bump the chain version number? The Omnibus version is updated in bulk when a new release is ready.

If it's a hassle I can fix it before I merge, just let me know :)

**Comment by rodri-r** [comment]
Changing now, thought you needed that changed from one of your last comments :)

**Comment by rodri-r** [comment]
@tombeynon I think it is good now, although Kava test run is failing for some reason :D

**Pull request merged**
