### PR TITLE
Upgrade Evmos to v15.0.0

### PR DESCRIPTION
**Pull request by CharlesJUDITH**
Evmos will be upgraded to v15.0.0 at block https://www.mintscan.io/evmos/block/16946771

Estimated Time: Nov 6th 2023, 16:59:43

Proposal: https://www.mintscan.io/evmos/proposals/240

### CODE REVIEW

**Comment by tombeynon** [comment]
`ghcr.io/akash-network/cosmos-omnibus:v0.4.1-rc1-evmos-v15.0.0`

**Comment by hitchhooker** [comment]
its normal to not bea ble to sync using v.14.1.0 right now?

**Comment by CharlesJUDITH** [comment]
@hitchhooker can you give more details?

**Comment by CharlesJUDITH** [comment]
if your node is still is v14.1.0, you need to use the v15.0.0 because the previous version is not compatible with the new one: https://www.mintscan.io/evmos/parameters

Check the binary version on Mintscan, when it's compatible you have all the versions that are listed.

**Comment by hitchhooker** [comment]
Apparently there was an issue with statesyncing, end up using alternative snapshot to get it work.

**Pull request merged**
