### PR TITLE
Update Akash default yml

### PR DESCRIPTION
**Pull request by 88plug**
- Fixes persistent storage config
- Set persistent storage with SSD as default
- Set default storage to 1Gi 
- Explain Storage options clearly to user
- Update min UAKT to 10,000 ; current value too low
- Cleanup dcloud name

### CODE REVIEW

**Comment by tombeynon** [comment]
Thank you @88plug! I need to check if we're okay making persistent storage the default, as it previously had a couple of caveats. I'll get this merged ASAP

**Comment by andy108369** [comment]
I am not sure if defaulting to the persistent storage is a good ida.

The problem with the PVs (physical volumes aka persistent storage aka ceph) by default happens when it gets 100% full for the tenant.
What happens is that the application simply stops writing and ends hanging dead until the owner notices & redeploys it.

This, however, does "heal" automatically when the ephemeral storage is in use since the kubelet watches and restarts the pod when it hits 100% of the ephemeral kind of volume (vs the PV one).

Another issue is that persistent storage is often way slower than the ephemeral storage which is no bueno for the nodes/validators. `beta3` (aka `NVMe`) would probably do better https://docs.akash.network/providers/build-a-cloud-provider/helm-based-provider-persistent-storage-enablement/storage-class-types

**Comment by 88plug** [comment]
Can revert to persistent storage commented out. Still need the other changes. beta2 is SSD and that is the minimum required for a node, and the SDL now includes comment to the user.

**Comment by andy108369** [comment]
> Can revert to persistent storage commented out. Still need the other changes. beta2 is SSD and that is the minimum required for a node, and the SDL now includes comment to the user.

yeah, leave it commented out, keep `beta3` as the default (commented)

**Pull request closed without merging**
