### PR TITLE
introduce Elys network (testnet only atm)

### PR DESCRIPTION
**Pull request by andy108369**
- [ ] `CHAIN_JSON` should be fixed here https://github.com/elys-network/elys/issues/39

### CODE REVIEW

**Comment by andy108369** [comment]
# SDL

```
---
version: "2.0"

services:
  node:
    ## TODO image: ghcr.io/akash-network/cosmos-omnibus:v0.3.27-elys-v0.2.3
    image: andrey01/cosmos-omnibus:v0.3.27-elys-v0.2.3
    #image: ghcr.io/akash-network/cosmos-omnibus:v0.3.27-generic
    env:
      # - DEBUG=2
      - MONIKER=<Your Moniker>
      ## TODO: use this CHAIN_JSON link once https://github.com/elys-network/elys/issues/39 is sorted
      ## - CHAIN_JSON=https://raw.githubusercontent.com/cosmos/chain-registry/master/elys/chain.json
      - CHAIN_JSON=https://gist.githubusercontent.com/andy108369/727bb9d8612fc66e9db35eebf183afe3/raw/64b62a051e30ea0febf344d6d2a1125dad8dd03b/elys-chain.json
      - P2P_POLKACHU=1
      # TODO: Polkachu told me he'll enable the state-sync only for the mainnet Elys ...
      # Use snapshot provided by Polkachu until then https://polkachu.com/testnets/elys/snapshots
      - SNAPSHOT_URL=https://snapshots.polkachu.com/testnet-snapshots/elys/elys_73916.tar.lz4
      - SNAPSHOT_DATA_PATH=data
      ## - STATESYNC_POLKACHU=1
      ## - SNAPSHOT_POLKACHU=1
      - MINIMUM_GAS_PRICES=0uelys
      - ELYSD_CONSENSUS_DOUBLE_SIGN_CHECK_HEIGHT=10
      - PRUNING=custom
      - PRUNING_INTERVAL=10
      - PRUNING_KEEP_EVERY=2000
      - PRUNING_KEEP_RECENT=100
      ### state-sync node mode
      # do a snapshot every (2000*6)/60 = 200 minutes (having the block time is 6 seconds)
      - STATESYNC_SNAPSHOT_INTERVAL=2000
      - ELYSD_STATESYNC_SNAPSHOT_KEEP_RECENT=5
      #- BINARY_URL=https://github.com/elys-network/elys/releases/download/v0.2.3/elys._v0.2.3_linux_amd64.tar.gz
      #- BINARY_ZIP_PATH=elysd
      # Cosmovisor config
      - COSMOVISOR_ENABLED=1
      - DAEMON_ALLOW_DOWNLOAD_BINARIES=true
      - DAEMON_RESTART_AFTER_UPGRADE=true
      - DAEMON_LOG_BUFFER_SIZE=512
      - UNSAFE_SKIP_BACKUP=true
      # Key
      - S3_KEY=REDACTED
      - S3_SECRET=REDACTED
      #- S3_HOST=https://s3.filebase.com
      # https://eu1.storj.io
      # https://docs.storj.io/dcs/getting-started/gateway-mt#VcSll
      # https://docs.storj.io/dcs/api-reference/s3-compatible-gateway
      - S3_HOST=https://gateway.storjshare.io
      - KEY_PATH=elys-antares-validator
      - KEY_PASSWORD=REDACTED
    expose:
      - port: 26657
        as: 80
        to:
          - global: true
        #accept:
        #  - elys.yourdomain.com
      - port: 26656
        to:
          - global: true

profiles:
  compute:
    node:
      resources:
        cpu:
          units: 1
        memory:
          size: 8Gi
        storage:
          size: 100Gi
  placement:
    dcloud:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63
      pricing:
        node:
          denom: uakt
          amount: 10000

deployment:
  node:
    dcloud:
      profile: node
      count: 1
```

**Comment by andy108369** [comment]
There is upgrade to Elys Network testnet `v0.3.1` coming which will take place `Monday 17 April` at block `116000`, it will be worth waiting for it to happen and then update this PR to `0.3.1`.

Also need to wait until https://github.com/elys-network/elys/issues/39 gets sorted.

refs
- https://github.com/elys-network/elys/releases/tag/v0.3.1
- https://discord.com/channels/1049783263956324462/1055294069498200105/1096612853575847976

**Comment by cosmic-vagabond** [comment]
@andy108369 new PR to update to latest version (v0.4.0) https://github.com/akash-network/cosmos-omnibus/pull/463

**Comment by andy108369** [comment]
Replaced by https://github.com/akash-network/cosmos-omnibus/pull/463

**Pull request closed without merging**
