### PR TITLE
Update Injective to 1.11

### PR DESCRIPTION
**Pull request by CharlesJUDITH**
For more information:
https://www.mintscan.io/injective/proposals/231
https://www.mintscan.io/injective/blocks/34775000

### CODE REVIEW

**Comment by tombeynon** [comment]
Thanks so much, links are especially helpful. I'll make these 'future' update Draft PRs until the update time just so it's easy to see what is live and what isn't.

I'll create rc images for these later today

**Comment by tombeynon** [comment]
`ghcr.io/akash-network/cosmos-omnibus:v0.3.34-rc1-injective-v1.11-1685225746`

**Comment by tombeynon** [comment]
Update to v1.11.1-1685698280

`ghcr.io/akash-network/cosmos-omnibus:v0.3.34-rc2-injective-v1.11.1-1685698280`

**Comment by tombeynon** [comment]
@CharlesJUDITH the `rc` images aren't supposed to be added to the docs. They're a pre-release image so users can use the new version before it's merged. Once it's merged, the docs should reflect the new version, in this case `ghcr.io/akash-network/cosmos-omnibus:v0.3.34-injective-v1.11.1-1685698280`

This PR was correct before your most recent pushes, it just needed updating to v0.3.34. Please don't force-push unless it can't be avoided as it overwrites history. 

Do you want me to revert this to the version prior to these commits? It's just waiting for me to update it to v0.3.34 cut a new release.

**Comment by CharlesJUDITH** [comment]
> @CharlesJUDITH the `rc` images aren't supposed to be added to the docs. They're a pre-release image so users can use the new version before it's merged. Once it's merged, the docs should reflect the new version, in this case `ghcr.io/akash-network/cosmos-omnibus:v0.3.34-injective-v1.11.1-1685698280`
> 
> This PR was correct before your most recent pushes, it just needed updating to v0.3.34. Please don't force-push unless it can't be avoided as it overwrites history.
> 
> Do you want me to revert this to the version prior to these commits? It's just waiting for me to update it to v0.3.34 cut a new release.

OK I let you revert it then

**Comment by tombeynon** [comment]
Thanks @CharlesJUDITH - I'll get all these pending PRs merged soon.

**Pull request merged**
