### PR TITLE
feat(polkachu-api) Support new version v2

### PR DESCRIPTION
**Pull request by omniwired**
#650 

Please add your changes.

### CODE REVIEW

**Comment by omniwired** [comment]
@tombeynon the new v2 polkachu is missiing some of the features the v1 had.
For example: live peers.
I think we need to add a new "CHAIN_ID" variable, because this API needs it in this fashion:
- teritori and not teritori-1 (the actual chain id)

**Comment by tombeynon** [comment]
Thanks so much for kicking this off @omniwired! That's a bit unfortunate we can't look up the chain by ID anymore - we'll need to add a POLKACHU_CHAIN_ID variable since it doesn't seem to follow Chain Registry naming conventions. 

Noted that we'll need to use seeds instead of peers - that's something we needed to update anyway since seeds are much more reliable. 

I'll pick this up ASAP - expect next Monday.

**Comment by omniwired** [comment]
I will add POLKACHU_CHAIN_ID env var then!

**Comment by tombeynon** [comment]
Thanks again for this @omniwired - I made a couple minor adjustments but otherwise think we're good to go!

**Comment by omniwired** [comment]
Thanks for @tombeynon for all your contributions in the cosmos world.
I'm big fan of your work.

**Comment by tombeynon** [comment]
Really appreciate that @omniwired - thank you ❤️

**Pull request merged**
