### PR TITLE
Upgrade Akash to v0.30.0

### PR DESCRIPTION
**Pull request by CharlesJUDITH**
Akash will be upgraded to v0.30.0 at block 13880774.

https://dev.mintscan.io/akash/blocks/13880774

Estimated Target Date: Tue Nov 28 2023 14:25:16 GMT+0100 (GMT+01:00)

Proposal: https://dev.mintscan.io/akash/proposals/238

### CODE REVIEW

**Comment by tombeynon** [comment]
@CharlesJUDITH could you give me permission to edit PRs from StakeLab-Zone? I believe it's a checkbox on the bottom-right of this page. I've got a commit ready to bring this up-to-date with master

**Comment by CharlesJUDITH** [comment]
> @CharlesJUDITH could you give me permission to edit PRs from StakeLab-Zone? I believe it's a checkbox on the bottom-right of this page. I've got a commit ready to bring this up-to-date with master

I disabled the branch protection rule, that should be ok.

**Comment by tombeynon** [comment]
@CharlesJUDITH unfortunately not, does this help? https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork

**Comment by CharlesJUDITH** [comment]
https://github.com/orgs/community/discussions/5634 I don't have the options from the organization.

**Comment by tombeynon** [comment]
That's annoying they haven't fixed it yet! I'll open a new PR for now

**Comment by tombeynon** [comment]
Closing in favour of #693

**Pull request closed without merging**
